### ISSUE TITLE
Initial page load is still slow compared to original GH maps

### ISSUE THREAD

**Issue by easbar** [graphhopper/graphhopper-maps#132]
@boldtrn suggested the following:

 - [x] enable brotli/gzip
 - [ ] measure page load using: 
  - https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgraphhopper.com%2Fmaps%2F&tab=desktop
  - https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgraphhopper.com%2Fmaps2%2F&tab=desktop
  or lighthouse
 - [x] bundle size -> not much difference to old GH Maps
 - [ ] why are two icons loaded: /assets/favicon-16x16.png and /assets/apple-touch-icon-1024x1024.png
 - [x] ~~initially maptiler does 3 requests to fonts (3*43kb) - can we reduce to 1 request?~~ > we use raster tiles by default since #159
 - [x] ~~load map with raster tiles in background first: https://support.maptiler.com/i818-load-the-map-visually-more-quickly-using-a-raster-background but currently they are blurred!? -> https://support.maptiler.com/i851-incorrect-usage-of-512px-tiles~~ -> > we use OpenLayers with raster tiles by default since #159
 - [ ] profile in chrome
 - [x] try on latest FF94 as there were some [perf improvements](https://bugzilla.mozilla.org/show_bug.cgi?id=1732049) for a specific Mapbox GL JS case -> we use OpenLayers not Mapbox since #159
 - [x] ~~try without wrapper~~ -> we use OpenLayers without the react-map-gl wrapper since #159
 - [x] try raster -> we use OpenLayers with raster tiles by default since #159
 - [x] ~~try different vector tiles provider~~ -> we use raster tiles by default since #159

and I think we already figured that maptiler vector tiles are slow compared to mapbox, even on their website. However, this should not affect the page load when we use raster tiles?

**Comment by boldtrn** [comment]
As a side-note, if you look at the library size of leaflet vs. maplibre, it is significantly larger (contains all the code to render vector tiles :)).

https://bundlephobia.com/package/maplibre-gl@2.0.0-pre.5
https://bundlephobia.com/package/leaflet@1.7.1

**Comment by easbar** [comment]
Maybe it is worth looking at these experiments I did a while back again: https://github.com/easbar/gh_maps_experiments

**Comment by karussell** [comment]
When comparing PageSpeed for old vs. new then it seems we should also look how we can reduce the work for the main thread (2.7s vs. 0.1s) and "Total Blocking time" (0.8s vs. 0). Correlated to the task to profile this app in chrome, I think.

**Comment by boldtrn** [comment]
IMHO, the biggest thing to consider here is that you can't compare Leaflet to a vector tile library. Vector tiles move the actual render work to the client side, which increases the work the browser has do and also increases the page size. So I am not sure if this is something that could be fixed at all.

You can experiment with Tree Shaking etc., but I am not sure this will solve the underlying issue, just improve it.

**Comment by easbar** [comment]
After some discussions with @karussell  OpenLayers is still an option. Here I replaced Mapbox with OpenLayers (just the background layer, no markers, paths etc. yet):

http://gh-maps-react.s3-website.eu-central-1.amazonaws.com/ol_exp/

**Comment by karussell** [comment]
Wow, this is nicely fast :D. We could e.g. keep using Omniscale as our default and still switch to vector tiles for MVT (or my navi experiment).

> IMHO, the biggest thing to consider here is that you can't compare Leaflet to a vector tile library. 

The raster tiles are also slower when using mapbox/maplibre. And for the perceived slowness not only the time it takes is slower but also the responsiveness is worse (lower measureable FPS). I compared an uncached refresh (network tab -> disable cache + enabled "recording performance"):

 * openlayers raster: 0.5-1.5s and average FPS is ~45
 * master raster: 3.5-4.5s and average FPS is ~25
 * master vector: 5-7s and average FPS is ~25

The Openlayers demo currently has the minor advantage of http vs https. But still you can see that openlayers is less demanding. And with the "performance" tool in FF I also see that a FPS drop in case of the vector tiles remain a bit even after everything is updated.

> You can experiment with Tree Shaking etc., but I am not sure this will solve the underlying issue, just improve it.

I don't think this is DOM or react related. Probably more canvas vs. web GL (and also ff vs. chrome). E.g. I also tested with a desktop PC (with a better GPU than my laptop?) and chrome, then this difference was much smaller.

**Comment by easbar** [comment]
I just updated this branch to include the other raster tiles (even the ones that did not work with Mapbox, lyrk&wanderreitkarte), and I enabled vector tiles as well.

Can you add the api key for omniscale so we can test this too?

> The Openlayers demo currently has the minor advantage of http vs https.

But there should not be any difference in this regard if you compare
http://gh-maps-react.s3-website.eu-central-1.amazonaws.com/ol_exp/ vs
http://gh-maps-react.s3-website.eu-central-1.amazonaws.com/master/
?

Compared to graphhopper.com/maps2 the aws deployment also does not use zip etc.? I just checked pagespeed and got the following:

```
/ol_exp/bundle.js(gh-maps-react.s3-website.eu-central-1.amazonaws.com) | 5,750.1 KiB
/master/bundle.js(gh-maps-react.s3-website.eu-central-1.amazonaws.com) | 3,342.3 KiB
/maps2/bundle.js(graphhopper.com) | 368.0 KiB
```

So the hosted version is much smaller and the unzipped OL version is much bigger than the unzipped master version.

**Comment by karussell** [comment]
> So the hosted version is much smaller, and the unzipped OL version is much bigger than the unzipped master version

Ah, nice, so even more surprising that it is the fastest :) !

> Can you add the api key for omniscale so we can test this too?

Sure. But omniscale works only on graphhopper.com.

**Comment by easbar** [comment]
Possibly related: 

https://github.com/visgl/react-map-gl/issues/1529
https://github.com/visgl/react-map-gl/issues/1151
https://github.com/visgl/react-map-gl/issues/1000

Trying `asyncRender={true}` could be worthwhile.

**Comment by karussell** [comment]
> Trying asyncRender={true} could be worthwhile.

For my test I did a few months ago with the navi branch this did not help.

**Comment by easbar** [comment]
I think this is fixed with #159

**Comment by hy31337** [comment]
请问 OpenLayers ol-ext PerspectiveMap地图倾斜时 Feature图标文字怎么转正为平面视角？
May I ask how to convert the Feature icon and text to a flat perspective when the OpenLayers ol ext PerspectiveMap map is tilted?
examples：https://docs.mapbox.com/mapbox-gl-js/example/set-perspective/
